name: gdg_capstone_project_2025
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  data_connection_checker_tv: ^0.3.5-nullsafety
  
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  get_it: ^8.0.3
  formz: ^0.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
