// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCYbbiFoihEWkgUclsUMT3nzmkm08uSdA',
    appId: '1:1011092072320:web:ed5537356b3bc527918365',
    messagingSenderId: '1011092072320',
    projectId: 'gdg-capstone-project-2025',
    authDomain: 'gdg-capstone-project-2025.firebaseapp.com',
    storageBucket: 'gdg-capstone-project-2025.firebasestorage.app',
    measurementId: 'G-B7BVM7S890',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUT6saSlU23CDKRCsmbPp5rH0nFr6Rbmg',
    appId: '1:1011092072320:android:f8cbe48f26e94209918365',
    messagingSenderId: '1011092072320',
    projectId: 'gdg-capstone-project-2025',
    storageBucket: 'gdg-capstone-project-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLu0txLpxsnppqoWX7dz_ZPvdOEe0JrMY',
    appId: '1:1011092072320:ios:349df1112602a4aa918365',
    messagingSenderId: '1011092072320',
    projectId: 'gdg-capstone-project-2025',
    storageBucket: 'gdg-capstone-project-2025.firebasestorage.app',
    iosBundleId: 'com.example.gdgCapstoneProject2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLu0txLpxsnppqoWX7dz_ZPvdOEe0JrMY',
    appId: '1:1011092072320:ios:349df1112602a4aa918365',
    messagingSenderId: '1011092072320',
    projectId: 'gdg-capstone-project-2025',
    storageBucket: 'gdg-capstone-project-2025.firebasestorage.app',
    iosBundleId: 'com.example.gdgCapstoneProject2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCYbbiFoihEWkgUclsUMT3nzmkm08uSdA',
    appId: '1:1011092072320:web:482bdaf35858977d918365',
    messagingSenderId: '1011092072320',
    projectId: 'gdg-capstone-project-2025',
    authDomain: 'gdg-capstone-project-2025.firebaseapp.com',
    storageBucket: 'gdg-capstone-project-2025.firebasestorage.app',
    measurementId: 'G-4XS6068CDN',
  );
}
